### ISSUE TITLE
оптимізація

### ISSUE THREAD

**Issue by pecourses** [andreyturenko/hw-js-array#1]
https://github.com/andreyturenko/hw-js-array/blob/15393a822c76ec4759c66e44b334945703e392a4/assets/js/hw-array.js#L42
- щоб не виконувати перевірки на кожній ітерації циклу, можна збільшувати лічильник кожен раз на 2

**Comment by andreyturenko** [comment]
for (let i = 0; i < varArrays.length; i += 2) {
  if (i % 2 === 0) {
    console.log("Elements with even indexes :>> ", varArrays[i]);
  }
}

**Comment by andreyturenko** [comment]
Зайву частину прибрав
for (let i = 0; i < varArrays.length; i += 2) {
  console.log("Elements with even indexes :>> ", varArrays[i]);
}
