### ISSUE TITLE
неочевидний код

### ISSUE THREAD

**Issue by pecourses** [andreyturenko/hw-js-array#2]
https://github.com/andreyturenko/hw-js-array/blob/15393a822c76ec4759c66e44b334945703e392a4/assets/js/hw-array.js#L130-L131
- можливо, забули дописати код. Неочевидний код дуже заплутує при підтримці застосунку: "ніби-то і не треба, але раптом це щось складне, незрозуміле, але важливе")

**Comment by andreyturenko** [comment]
Дякую за прискіпливу перевірку, коли не очевидні речі, стають очевидними

if (number <= 1) return false;
if (number === 2) return true;
// --------------------------------------------------
function isPrime(number) {
  if (number <= 1) return false;
  if (number === 2) return true;

  const sqrtNum = Math.sqrt(number);
  for (let i = 2; i <= sqrtNum; i++) {
    if (number % i === 0) return false;
  }
  return true;
}

const arrOfValue = [12, 18, 42, 33, 1, 25];

const allSimple = arrOfValue.every((number) => isPrime(number));
console.log("Array elements simple number :>> ", allSimple);
